spring:
  security:
    oauth2:
      client:
        registration:
          cloudentity:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
        provider:
          cloudentity:
            user-info-authentication-method: form
logging:
  level:
    root: INFO
    org.springframework.web.client: DEBUG